name: Build Image

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Build image (api)
        run: docker build . --file Dockerfile --tag image --target api
      - name: Build image (conversion)
        run: docker build . --file Dockerfile --tag image --target conversion